### ISSUE TITLE
Using SSE with spring security 

### ISSUE THREAD

**Issue by haider-ali** [ralscha/sse-eventbus#11]
Is it possible to keep the event emitter in session  so message can be sent to specific user

**Comment by ralscha** [comment]
I guess this could work, then you no longer need this library. 
How do you access the sessions?

**Comment by haider-ali** [comment]
Actually i have a scenario where instead of pushing notification to all the user i have to push only to specific user for for that either i have to put it in session or static map with key as username , for session i was think creating a custom userprinciple class and on SSE connection updating that userpricple  , when on server side i can iterate on all the users that are currently online and get appropriate emitter to push notification

**Comment by ralscha** [comment]
In that case you don't need the library, because your application manages all the SseEmitter instances.

If you want to use the library you could follow this approach. When a client registers, instead of just subscribing him to the default event your application subscribes him to an event that is unique for this particular user.
For example the user id or username or something else that is unique.

```java
	@GetMapping("/register/{id}")
	public SseEmitter register(@PathVariable("id") String id) {		
                userIdentification = // user id or username of logged in user
                // subscribe this user to the default topic and to a special user topic
		return this.eventBus.createSseEmitter(id, SseEvent.DEFAULT_EVENT, userIdentification );
	}
```

Then, from other parts of the application you can send an event to one particular user
```java
// sending message to one user 
userIdentification = ....
this.eventBus.handleEvent(SseEvent.of(userIdentification, some_data));
```

The tricky part is on the client where you have to add an event listener for this special topic.
Unfortunately the `message` event only catches messages sent to the default topic. 
Somehow the client needs to know the unique identification of the user 

```js
const specialUserTopic =  // same as userIdentification  on the server
const uuid = uuid();
const eventSource = new EventSource(`/register/${uuid}`);
eventSource.addEventListener(specialUserTopic, response => {
	//handle the response from the server
}, false);
```
